services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    working_dir: /workspace
    shm_size: 2gb
    volumes:
      - ./:/workspace
    environment:
      MAVEN_OPTS: -Dmaven.repo.local=/workspace/.m2
      CRYPTOPRO_AUTO_IMPORT: "false"
    command: >
      bash -lc
      "mvn test
      -Dheadless=true
      -Dchrome.binary=/usr/bin/google-chrome"
